### ISSUE TITLE
Skill overhaul (part 2)

### ISSUE THREAD

**Issue by BenDawgAK** [tofu99/GR-2.28.2020#10]
A brief checklist of the overhaul

- [x] Write rules

- [x] Add example skill keywords

- [x] Reformat the skills

**Comment by CoconutMacaroon** [comment]
I find [this tool](https://www.tablesgenerator.com/markdown_tables) helpful for making Markdown tables. Although this is just my opinion.

**Comment by BenDawgAK** [comment]
thanks man!
that'll help alot

**Comment by CoconutMacaroon** [comment]
These branches are confusing  :) Just make a PR, and we just won't merge it until it is done, as you can commit multiple times to a PR, before it is merged

**Comment by BenDawgAK** [comment]
yeah okay. Multiple people can contribute right?

**Comment by CoconutMacaroon** [comment]
Yep. So you create a PR, we do the work in the PR, and then once it is done, we merge it.

**Comment by CoconutMacaroon** [comment]
Oops. Create a FORK, then do the work in the fork, then we merge the fork. I was totally wrong before.

**Comment by BenDawgAK** [comment]
The PR has been finished, i'll wait until it's merged to close this

**Comment by BenDawgAK** [comment]
alrighty, the first pr has been merged, open the next one

**Comment by CoconutMacaroon** [comment]
See this #12 for converting it to a table

**Comment by BenDawgAK** [comment]
no, your good

**Comment by BenDawgAK** [comment]
Finished!
