### ISSUE TITLE
Add list of sample skills

### ISSUE THREAD

**Issue by CoconutMacaroon** [tofu99/GR-2.28.2020#13]
Can we have a sample list of skills? In the `Example Effect Table` and the `Example Item Table`, the rules references various skills. But we don't have a list of example skills. I propose that it would have `Strength`, ` Wisdom`, `Intelligence`,  `Dexterity`, `Chairmsma`, `Constitution `, `Knife Fighting`, `Poisoning`, `Sharp Shooting`, and `Archery`. I also think we should have the [Tomato Analogy](https://www.reddit.com/r/dndnext/comments/409dnq/explaining_ability_scoresor_a_joke_about_tomatoes/?utm_source=share&utm_medium=web2x) to explain the first six. If we want this, I could help make it.

**Comment by BenDawgAK** [comment]
Sure.
Add Keywords (about 2) to each of these.
I.E. Charisma could be `Mental`  `power`
Knife fighting is a `combat`  `melee` c-skill

**Comment by CoconutMacaroon** [comment]
Can we add `ranged` to knife fighting as well (as they can be thrown)?

**Comment by BenDawgAK** [comment]
good idea!
I think for the most part, 2-3 is where we should limit keywords, with C-skill being a free thing.

**Comment by CoconutMacaroon** [comment]
OK. I am working on this. I can start a PR once it is done.

**Comment by CoconutMacaroon** [comment]
How is this:

| Skill Name     | Description of Skill                                 | Associated Keywords | Conditions                      |
|----------------|------------------------------------------------------|---------------------|---------------------------------|
| Strength       | The ability to crush a tomato                        | Physical            |                                 |
| Wisdom         | Knowing NOT to put a tomato in a fruit salad.        | Mental              |                                 |
| Intelligence   | Knowing that a tomato is a fruit.                    | Mental              |                                 |
| Dexterity      | The ability to dodge a tomato being thrown at you.   | Physical            |                                 |
| Chairmsma      | Being able to sell a tomato-based fruit salad.       | Mental, Power       |                                 |
| Constitution   | The ability to eat a rotten tomato and not get sick. |                     |                                 |
| Knife Fighting | Removing/creative curses (on items)                  | Physical            | Have one or more knives         |
| Poisoning      | Anything fighting/battle/combat related              |                     | Having poison/venom             |
| Sharp Shooting | Being able to aim accurately with ranged weapon      | Ranged              | Have one or more ranged weapons |
| Archery        | Using a bow and arrow                                | Physical, Ranged    | A bow and arrow(s)              |

**Comment by BenDawgAK** [comment]
looks great! you might want to clean up `Knife Fighting` and `Poisioning`

**Comment by BenDawgAK** [comment]
also add combat to `Knife Fighting`, `Sharpshooting` and `Archery`, as that is one of the keywords

**Comment by CoconutMacaroon** [comment]
Thanks! And for the knife fighting, thanks for noticing that.

**Comment by CoconutMacaroon** [comment]
What do you think? https://github.com/tofu99/GR-2.28.2020/pull/15/files?short_path=13d4fc3#diff-13d4fc3c0cab3b68e4db9b518ae918ba

**Comment by BenDawgAK** [comment]
add physical to constitution, and i'll change curse to debuff, then add that to poison

**Comment by CoconutMacaroon** [comment]
What do you mean "Change curse to debuff, then add that to poison"?

**Comment by BenDawgAK** [comment]
i'm changing the curse keyword to the debuff keyword so it's not as specific

**Comment by CoconutMacaroon** [comment]
I approved your PR. Do you think my PR is ready, or are there any other changes I should make?

**Comment by BenDawgAK** [comment]
ready to be closed!
