### ISSUE TITLE
Improvised Weapons

### ISSUE THREAD

**Issue by CoconutMacaroon** [tofu99/GR-2.28.2020#21]
Do you want improvised weapons? If we want it, I would suggest that it just be the DM gets to chose the damage type and the skill, but there is no bonus. Or should we just say no improvised weapons?

**Comment by BenDawgAK** [comment]
Weapons can be left up to the Gm's description. 
Usually i just use the closest analogue,
So in 5e terms ruling a table leg as a club,
a think branch as a qaurterstaff, 
a butchers cleaver as a dagger that deals slashing.
Just use the closest thing in the rules

**Comment by BenDawgAK** [comment]
i'll make a PR to add a couple new weapons to the table, so clubs, large swords, explosives, ETC.

**Comment by BenDawgAK** [comment]
Sorry, i'm bad at editing markdown tables. this'll take a while

**Comment by BenDawgAK** [comment]
I'll hold off on the changes, as seeing that that is an example table the GM can improvise with what we have
