### ISSUE TITLE
Bonus/debuff question

### ISSUE THREAD

**Issue by CoconutMacaroon** [tofu99/GR-2.28.2020#8]
The bonus/de-buff changes the number of dice you can re-roll. Can these be cured? I am wondering about the indefinite ones? Maybe with a DC something medicine check?

**Comment by tofu99** [comment]
I will have to think about that because certain effects can't be medically cured like Hex or Bad Luck or stuff like that. I think the things that end the Indefinite Effects will will change depending on what sort of effect it is.

**Comment by CoconutMacaroon** [comment]
Just as an idea, we could add a column that adds how it could be cured. As an example, some things, like an arrow wound, could be cured with a `DC xx` medicine check (specified in the item description. If there are going to be spells added at some point, others like Hex could be cured with something like `Wish`. Up to you, but I wouldn't want my character to be permanently turned into a frog, with no way to undo it.

**Comment by BenDawgAK** [comment]
Add a skill keyword, `healing` and each debuff has a target keyword, so I.E. Hex could be cured with a skill with healing, supernatural

**Comment by BenDawgAK** [comment]
The keyword system aims to cut down on skill confusion and add more distinction

**Comment by CoconutMacaroon** [comment]
That makes sense... going with what @BenDawgAK  proposed, could we add `Healing, basic` and `Healing, supernatural` to the skill list mentioned in issue #10? And then each weapon would list the relevant skill (from the list) and the DC. What do we think?

**Comment by BenDawgAK** [comment]
as you would imagine, i'm on board. I'll make sure to add a `weapon` or `conditional` keyword to the list when i write it up

**Comment by BenDawgAK** [comment]
also, i'll add the `combat` keyword for skills tied to combat

**Comment by CoconutMacaroon** [comment]
Is there a branch for work on Part Two...? If so, I can help add skills to the list...

**Comment by BenDawgAK** [comment]
uh... lemme try to set that up
i'm new so, ya know.

**Comment by CoconutMacaroon** [comment]
Between `Curse`, `Healing`, and `Supernatural`, I think that is sufficient. See [this table](https://github.com/tofu99/GR-2.28.2020/blob/master/Russian%20Roulete%20RPG%20system%20rules.md#example-keywords)
